### ISSUE TITLE
Compatibility fix for Gnome 46

### ISSUE THREAD

**Issue by mendres82** [nlpsuge/gnome-shell-extension-another-window-session-manager#103]
Running this extension with Gnome 46 on openSUSE Tumbleweed gave me an error. Fortunately, it was quite easy to get around the issue. I just had to edit _indicator.js_ and change lines 297 and 298 from `add_actor ` to `add_child `.

**Comment by MorbidShell** [comment]
Sorry to butt in, but you could just make a pull request with the changes. :p

**Comment by mendres82** [comment]
I created the pull request.

**Comment by cmeissner** [comment]
#104 works also with Fedora 40. After adjusting `shell-version` in `metadata.json` and re-login the extension works well

**Comment by OsoRojo** [comment]
While this fix works (changing lines 297 and 298 and fixing the `shell-version` in `metadata.json`), it seems to break session logout.  When the logout dialog appears, clicking logout does nothing.  You can still logout using `gnome-session-quit -force`, but that's not ideal.  Disabling the extension restores normal logout behavior, so it does seem to be related to the extension.

**Comment by mendres82** [comment]
> ..., it seems to break session logout.  When the logout dialog appears, clicking logout does nothing.  You can still logout using `gnome-session-quit -force`, but that's not ideal.

Cannot reproduce on openSUSE Tumbleweed (Gnome 46.1) and Slowroll (Gnome 46.0). Both on Wayland.

**Comment by OsoRojo** [comment]
> > ..., it seems to break session logout.  When the logout dialog appears, clicking logout does nothing.  You can still logout using `gnome-session-quit -force`, but that's not ideal.
> 
> Cannot reproduce on openSUSE Tumbleweed (Gnome 46.1) and Slowroll (Gnome 46.0). Both on Wayland.

Just reproduced on a clean Fedora 40 Silverblue VM (Gnome 46.1 on Wayland) with no other extensions installed and the above mods in place.  Note that the original report was not from Silverblue, but desktop proper with the same versions.  

Disabling the plugin restores normal behavior.  

Sorry, should have noted the distro I guess.

**Comment by nlpsuge** [comment]
> While this fix works (changing lines 297 and 298 and fixing the `shell-version` in `metadata.json`), it seems to break session logout. When the logout dialog appears, clicking logout does nothing.

Hi, a new version that supports Gnome 46 has been approved, could you please test it again after updating? I think it might be fixed.

**Comment by OsoRojo** [comment]
So it's... sort of fixed, yes.  I get the standard "you will be logged out after 60 seconds"...

![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/1007424/76c6f8a8-1acc-473a-b491-747e539e7741)

And then after clicking logout via AWSM, I get this:

![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/1007424/f1b6a0fd-3c9f-4256-850d-7fa65d0ec9a2)

Clicking Logout Now DOES log me out, so that's good.  But there are no other applications listed, and I don't have anything running but Software and Extensions.  It's something I've never seen before.

To be clear, it's not a huge problem.  It does allow both logout and reboot after it comes up, but the fact that no applications are listed seemed a bit odd.   If this is just what we have to do now for some known reason I'm totally fine with that.  

Thoughts?

**Comment by ghost** [comment]
@OsoRojo I've had that exact same problem on Fedora 39 / Gnome 45 already and it's still the same after the update to Fedora 40 / Gnome 46, so I don't think this is anything new.
As you say, I always need to click "Log out now" / "Reboot now" manually.
If applications are still running, they get closed, but then the "Running applications" window just sits there doing nothing.

**Comment by nlpsuge** [comment]
@sadamczyk @OsoRojo I've uploaded a new version that fixes the issue you mentioned. I'm waiting for it to be approved.

**Comment by OsoRojo** [comment]
Verified fixed on clean Silverblue VM for both logout and reboot!  Thank you!!

**Comment by ghost** [comment]
Just updated and it's fixed for me as well. Thanks for the quick fix! :)
