### ISSUE TITLE
Forward slash in Session Name

### ISSUE THREAD

**Issue by barnscott** [nlpsuge/gnome-shell-extension-another-window-session-manager#29]
If user saves a session-name that includes a forward-slash, the session-name does not appear in the panel-menu's session list.

When checking the session directory at `~/.config/another-window-session-manager/sessions` I observed that using the forward-slash created a folder.

I dont have a suggested fix / workaround. A solution might be any of the following:
- replacing forward-slash with dash
- adding double-quote to the session name when a forward-slash exists
- a message that inhibits user from saving a session with a forward-slash

**Comment by nlpsuge** [comment]
Hi @barnscott ,

Thanks for reporting this issue.

I fix this issue by inhibiting the users from saving a session with a forward-slash. 

Thanks for your suggestion :)

**Comment by scarlion1** [comment]
I am seeing a ton of errors related to this though, in the journal from _gnome-shell_.  Anytime there's a forward slash in the window title, it's a problem.  So, that's every web browser window with a  GitHub page since those all have the title with <tt>&lt;author&gt;<b>/</b>&lt;app&gt;</tt> in them, and so on.  15,975 journal entries in not even 10 days!

Further, from the indicator icon menu, I can still use "Save open windows" and it seems to save the session just fine and puts an entry for the session in the menu.  Was that supposed to be inhibited?

Either way, I hope the mass of error messages could be addressed, and nothing inhibited would be ideal, right?  some of the suggestions from barnscott still seem relevant.  I'd think the session name should always be in double-quotes?  That's probably a good practice like with bash, but then again I got no idea what are best practices for JS! 😛

Thanks,
Best Regards

Example:
<pre>Dec 28 17:07:24 throne gnome-shell[404612]: [ERROR  ][Another window session manager] undefined: Error: 
Cannot remove '/home/scar/.config/another-window-session-manager/currentSession/firefox/0x2400046 (Forward slash in Session Name · Issue #29 · nlpsuge': Is a directory
                                            
Stack trace:
  removeFile@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/utils/fileUtils.js:263:23
  _removeOrphanSessionConfigs/&lt;@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:423:31
  listAllSessions@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/utils/fileUtils.js:179:29
  async*_removeOrphanSessionConfigs@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:419:23
  _cleanUpSessionFileByWindow@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:402:14
  _connectSignalsToCleanUpSessionFile/unmanagingId&lt;@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:368:22
  @resource:///org/gnome/shell/ui/init.js:21:20</pre>
