### ISSUE TITLE
Dragging windows becomes choppy when the extension is enabled

### ISSUE THREAD

**Issue by rwjack** [nlpsuge/gnome-shell-extension-another-window-session-manager#59]
The extension seems to be somehow impacting performance. The screencast doesn't record window movement for some reason. The only thing visible is during the last 3 seconds - showing how smooth window dragging is with the extension disabled. Otherwise window dragging is choppy and extremely delayed.

Occurs on: Pop!_OS 22.04 LTS | GNOME Shell 42.3.1

https://user-images.githubusercontent.com/59068073/189334804-581f939e-00f5-46d3-b7b9-edc2c4c7746e.mp4

**Comment by rwjack** [comment]
https://user-images.githubusercontent.com/59068073/189335535-b5eb6c71-1b97-4e23-956a-169cf01afdde.mp4

**Comment by nlpsuge** [comment]
> window dragging is choppy and extremely delayed

That's because it connects the signal `position-changed` to save window position to a local file, which really does not take too many time. 

But if you drag a window and move it, the window emits a lot of `position-changed` signals and this extension keep saving window position too, Gnome shell is just too busy to do it and can't handle other things. 

On my machine, the CPU usage of `gnome-shell` process could be very high if I drag and move a window constantly and quickly. BTW, how about the performance of dragging and resizing a window on your machine?

**Comment by nlpsuge** [comment]
Just as a workaround, you can disable `Stash and restore` to avoid this performance issue. Currently `Stash and restore` is used to restore `window tiling state` after Gnome shell restarts.

**Comment by rwjack** [comment]
That seems to have fixed the dragging issue, though I don't fully understand what disabling `Stash and restore` did exactly? My windows opened as saved, except those that I mentioned in another issue, which flip (eg. discord)

**Comment by nlpsuge** [comment]
> what disabling Stash and restore did exactly?

`Stash and restore` is used to save window states including `size` and `position` etc while the `size `or `position` is changed. After  disabling `Stash and restore`, this extension will no longer connect the signal `position-changed` and other signals to save window states:
https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/blob/739024b9be5b62bfda3ffa4b573e7bab3cdef52e/openWindowsTracker.js#L41-L51

**Comment by nlpsuge** [comment]
> My windows opened as saved

This is restored on startup.

`Stash and restore ` is only useful when **gnome-shell restarts** via `Alt+F2` then `press r` or `killall -3 gnome-shell` and this option is for X11.

**Comment by rwjack** [comment]
Understood, thank you!

**Comment by rwjack** [comment]
Wohoo! Thank you once again :D
