### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [nlpsuge/gnome-shell-extension-another-window-session-manager#89]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by nlpsuge** [comment]
Thank you, will do.

**Comment by sans-c** [comment]
I'd like to ask if there is any progress on this. Gnome45 ist out since a few weeks now. Any chance there will be an update anytime soon or better look for alternatives?

**Comment by nlpsuge** [comment]
> I'd like to ask if there is any progress on this. Gnome45 ist out since a few weeks now. Any chance there will be an update anytime soon or better look for alternatives?

Hi, 

Sorry for the delay, no progress for now.

But I should have time to start to migrate it to Gnome 45 recently.

**Comment by benne3333** [comment]
Would be great! One of my most important extensions :-)

**Comment by nlpsuge** [comment]
Hi,

I'm preparing to release a new version that supports for Gnome 45 ([this PR](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/pull/93)) today. 

----

Please note that due to [gnome-shell 45 does not export `EndSessionDialog`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/a42f7c23842ba186655f201db7edaf4b24590604/js/ui/endSessionDialog.js#L233), the flowing features do not work:
* [Restore previous apps and windows at startup](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/tree/main-gnome-45#restore-previous-apps-and-windows-at-startup) .
**Workaround**: I suggest to backup `currentSession` <details><summary></summary>Using `cp -r ~/.config/another-window-session-manager/currentSession ~/.config/another-window-session-manager/currentSession-bak` </details>before Log out/Reboot/Shutdown the computer, otherwise session files in `currentSession` will be removed automatically.  Next time after logging in, rename the backup to `currentSession` <details><summary></summary>Using `mv ~/.config/another-window-session-manager/currentSession-bak/ ~/.config/another-window-session-manager/currentSession`</details>. And then run the following command to restore the previous session: 
`gdbus call --session --dest org.gnome.Shell.Extensions.awsm --object-path /org/gnome/Shell/Extensions/awsm --method org.gnome.Shell.Extensions.awsm.Autostart.RestorePreviousSession "{'removeAfterRestore': <false>}"`
* [Auto close session](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#auto-close-session)
This feature is not working, so the original end session dialog of Gnome will be popped up.

After [this MR](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2997) is merged, the above feature will be supported automatically based on the MR.

**Comment by freddyw** [comment]
Being doing some first testing, looking good so far. Thank you very much, this means I can upgrade my main (Fedora) laptop next Tuesday!!

**Comment by g1bber1sh** [comment]
works for me as well!
thank you

**Comment by nlpsuge** [comment]
> Hi,
> 
> I'm preparing to release a new version that supports for Gnome 45 ([this PR](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/pull/93)) today.
> 
> Please note that due to [gnome-shell 45 does not export `EndSessionDialog`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/a42f7c23842ba186655f201db7edaf4b24590604/js/ui/endSessionDialog.js#L233), the flowing features do not work:
> 
> * [Restore previous apps and windows at startup](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/tree/main-gnome-45#restore-previous-apps-and-windows-at-startup) .
>   **Workaround**: I suggest to backup `currentSession` Using `cp -r ~/.config/another-window-session-manager/currentSession ~/.config/another-window-session-manager/currentSession-bak` before Log out/Reboot/Shutdown the computer, otherwise session files in `currentSession` will be removed automatically.  Next time after logging in, rename the backup to `currentSession` Using `mv ~/.config/another-window-session-manager/currentSession-bak/ ~/.config/another-window-session-manager/currentSession`. And then run the following command to restore the previous session:
>   `gdbus call --session --dest org.gnome.Shell.Extensions.awsm --object-path /org/gnome/Shell/Extensions/awsm --method org.gnome.Shell.Extensions.awsm.Autostart.RestorePreviousSession "{'removeAfterRestore': <false>}"`
> * [Auto close session](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#auto-close-session)
>   This feature is not working, so the original end session dialog of Gnome will be popped up.
> 
> After [this MR](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2997) is merged, the above feature will be supported automatically based on the MR.

It's still in review. I hope it can be approved today.

**Comment by nlpsuge** [comment]
The last review was rejected. I've submitted a fixed version and am awaiting approval, hoping it can be approved as soon as possible.

However, the `main-gnome-45+` branch, which supports Gnome 45, is fine to use.
