### ISSUE TITLE
SyntaxError on installation via extension manager in GNOME 45 on Ubuntu 23.10

### ISSUE THREAD

**Issue by g1ronn1mo** [nlpsuge/gnome-shell-extension-another-window-session-manager#94]
## Description
Attempting to install the `another-window-session-manager` extension via the `extension manager` results in a SyntaxError related to import declarations.

## Steps to Reproduce
1. Open the `extension manager`.
2. Attempt to install `another-window-session-manager`.
3. Observe the error message.

## Expected Behavior
The extension should install without any syntax errors.

## Actual Behavior
The installation process is interrupted by the following error message:

```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
@file:///home/bene/.local/share/gnome-shell/extensions/another-[window-session-manager@gmail.com](mailto:window-session-manager@gmail.com)/prefs.js:4:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

## System Information
- **GNOME version**: 45
- **Ubuntu version**: 23.10
- **Extension version**: 41
- **Installation method**: Extension manager

## Potential Causes
It seems that there may be an issue with how the imports are being handled within the `prefs.js` file of the extension.

## Suggested Fix
It might be necessary to review the `prefs.js` file to ensure that import declarations conform to the ES6 module standards.

---

**Comment by nlpsuge** [comment]
This is because the version on https://extensions.gnome.org/ does not support Gnome 45 yet. 

Please see this issue https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/issues/89.

Gnome 45 version is in review. It hope it can be approved as soon as possible.

But you can download branch `main-gnome-45+` and copy the content to `~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com`. The code itself is OK to use now.

**Comment by tagirb** [comment]
Just updated it via Gnome extension manager and it's working fine. Thanks a lot!
